[config]
schemaVersion = "0.0.1"

[package]
namespace = "the_tavern"
name = "AutogenRundown"
versionNumber = "0.80.5"
description = "Rundown generation mod for GTFO. New rundowns generated daily, weekly, monthly, and each season."
websiteUrl = "https://github.com/brgmnn/autogen-rundown"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_GTFO = "3.2.1"
dakkhuza-MTFO = "4.6.2"
dakkhuza-DakGeos = "0.3.8"
TheDoggyDoge-DogsTilePack = "1.3.0"
donan3967-donan3967_geo_pack_1 = "1.1.1"
donan3967-donan3967_geo_pack_2 = "1.3.2"
Flowaria-FlowGeos = "0.9.3"
ProjectZaero-ZaeroGeos = "0.6.0"
Red_Leicester_Cheese-CheeseGeos = "0.5.2"
Sam_D_B-SamGeos = "2.0.21"
Sam_D_B-SamGeosV2 = "1.0.0"
hirnukuono-AdvancedWardenObjective = "2.4.0"
hirnukuono-EEC_H = "1.8.21"
Inas07-EOSExt_Reactor = "1.0.7"
Inas07-EOSExt_SecuritySensor = "1.1.7"
Inas07-ExtraObjectiveSetup = "1.6.11"
Inas07-ExtraSurvivalWaveSettings = "1.1.3"
Inas07-LocalProgression = "1.3.7"

[publish]
repository = "https://thunderstore.io"
communities = ["gtfo"]
# categories = ["rundown-mods", "rundowns"]
categories = []
